package com.bolivar.comunes.poc_liquidacion.commons.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-11T17:31:40.817-05:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://www.segurosbolivar.com/AutosWebService/1.0", name = "AutosPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AutosPort {

    @WebMethod(action = "listaDeCiudades")
    @WebResult(name = "listaDeCiudadesResponse", targetNamespace = "http://www.segurosbolivar.com/autos/dto/crea", partName = "ListaCiudadesResponse")
    public ListaDeCiudadesResponse listaDeCiudades(
        @WebParam(partName = "ListaCiudadesInput", name = "listaDeCiudadesRequest", targetNamespace = "http://www.segurosbolivar.com/autos/dto/crea")
        ListaDeCiudadesRequest listaCiudadesInput
    ) throws FaultMessage;

    @WebMethod(action = "liquidarPrima")
    @WebResult(name = "liquidarPrimaResponse", targetNamespace = "http://www.segurosbolivar.com/autos/dto/crea", partName = "LiquidarPrimaResponse")
    public LiquidarPrimaResponse liquidarPrima(
        @WebParam(partName = "LiquidarPrimaInput", name = "liquidarPrimaRequest", targetNamespace = "http://www.segurosbolivar.com/autos/dto/crea")
        LiquidarPrimaRequest liquidarPrimaInput
    ) throws FaultMessage;

    @WebMethod(action = "crearCotizacion")
    @WebResult(name = "crearCotizacionResponse", targetNamespace = "http://www.segurosbolivar.com/autos/dto/crea", partName = "CrearCotizacionResponse")
    public CrearCotizacionResponse crearCotizacion(
        @WebParam(partName = "CrearCotizacionInput", name = "crearCotizacionRequest", targetNamespace = "http://www.segurosbolivar.com/autos/dto/crea")
        CrearCotizacionRequest crearCotizacionInput
    ) throws FaultMessage;
}
