package com.bolivar.comunes.poc_liquidacion.commons.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-11T17:31:40.835-05:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "AutosService",
                  wsdlLocation = "file:src/main/resources/static/AutosServiceNuevo.xml",
                  targetNamespace = "http://www.segurosbolivar.com/AutosWebService/1.0")
public class AutosService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.segurosbolivar.com/AutosWebService/1.0", "AutosService");
    public final static QName AutosPortBinding = new QName("http://www.segurosbolivar.com/AutosWebService/1.0", "AutosPortBinding");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/static/AutosServiceNuevo.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutosService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/static/AutosServiceNuevo.xml");
        }
        WSDL_LOCATION = url;
    }

    public AutosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutosService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AutosService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AutosService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AutosService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AutosPort
     */
    @WebEndpoint(name = "AutosPortBinding")
    public AutosPort getAutosPortBinding() {
        return super.getPort(AutosPortBinding, AutosPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutosPort
     */
    @WebEndpoint(name = "AutosPortBinding")
    public AutosPort getAutosPortBinding(WebServiceFeature... features) {
        return super.getPort(AutosPortBinding, AutosPort.class, features);
    }

}
